[config]

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.spicetify]
input_path = '/home/artrix/dotfiles/.config/matugen/templates/spicetify.template.ini'
output_path = '/home/artrix/.config/spicetify/Themes/matugen/color.ini'

[templates.nushell-dank16]
input_path = '/home/artrix/dotfiles/.config/matugen/templates/nushell-dank16.template.nu'
output_path = '/home/artrix/.cache/theme/theme.nu'

[templates.starship-dank16]
input_path = '/home/artrix/dotfiles/.config/matugen/templates/starship-dank16.template.toml'
output_path = '/home/artrix/.config/starship/starship.toml'

[templates.zen-userchrome]
input_path = '/home/artrix/dotfiles/.config/matugen/templates/zen-userchrome.template.css'
output_path = '/home/artrix/.config/DankMaterialShell/zen.css'

[templates.zellij]
input_path = '/home/artrix/dotfiles/.config/matugen/templates/zellij.template.kdl'
output_path = '/home/artrix/.config/zellij/themes/dank-material.kdl'

[templates.opencode-dank16]
input_path = '/home/artrix/dotfiles/.config/matugen/templates/opencode-dank16.template.json'
output_path = '/home/artrix/.config/opencode/themes/dank16.json'
