[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.ghostty]
input_path = './templates/ghostty.template'
output_path = '~/dotfiles/.config/ghostty/theme'

[templates.gtk3]
input_path = './templates/gtk.template.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk.template.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.discord-midnight]
input_path = './templates/discord-midnight.template.css'
output_path = '~/.config/vesktop/themes/midnight.theme.css'


[templates.qt5ct]
input_path = './templates/qtct-colors.template.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.template.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.colors]
pre_hook = "mkdir ~/.cache/theme"
input_path = './templates/colors.template.css'
output_path = '~/.cache/theme/colors.css'

[templates.starship]
input_path = './templates/starship.template.toml'
output_path = '~/.config/starship.toml'

[config.custom_keywords]
font_mono = "JetBrainsMono Nerd Font Mono"
font_sans = "Segoe UI"
