use std::{env, path::PathBuf};

pub fn get_root_dir(override_root: Option<PathBuf>) -> PathBuf {
    override_root.unwrap_or_else(|| {
        let home = env::var_os("HOME").unwrap_or_else(|| {
            eprintln!("WARN: HOME env var not found. Defaulting root_dir to current directory.");
            std::ffi::OsString::from(".")
        });
        PathBuf::from(home).join("dotfiles")
    })
}

pub const DISCLAIMER: &str = r#"
// This file is AUTOGENERATED, do not edit it directly
//
"#;
