[package]
name = "artrix-dots"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
handlebars = "4.0"
serde_json = "1.0"
walkdir = "2.0"
notify = "6.0"
tokio = { version = "1.0", features = ["full"] }
