model = "gpt-5.6-sol"
model_reasoning_effort = "low"
approvals_reviewer = "user"

[projects."/home/artrix/Documents/Code/osu-tournament-arena"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/ritherio"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/SonusScopeOverlay"]
trust_level = "trusted"

[projects."/home/artrix"]
trust_level = "trusted"

[projects."/home/artrix/dotfiles"]
trust_level = "trusted"

[projects."/home/artrix/dotfiles/.config/niri"]
trust_level = "trusted"

[projects."/home/artrix/Videos/recordings"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/clip-maker"]
trust_level = "trusted"

[projects."/home/artrix/Documents/School/honors-project"]
trust_level = "trusted"

[projects."/home/artrix/Downloads"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/doctype0"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/virelm"]
trust_level = "trusted"

[projects."/home/artrix/Videos/Screencasting"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/rust-universe"]
trust_level = "trusted"

[projects."/home/artrix/Documents"]
trust_level = "trusted"

[projects."/home/artrix/Nextcloud/Life"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/artrix.dev"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code"]
trust_level = "trusted"

[projects."/home/artrix/Documents/Code/tortillas"]
trust_level = "trusted"

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-08T23:40:03Z"
source_type = "local"
source = "/home/artrix/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[desktop]
followUpQueueMode = "steer"
git-branch-prefix = ""
conversationDetailMode = "STEPS_COMMANDS"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/home/artrix/Documents/Code/SonusScopeOverlay" = "zed"
"/home/artrix/Documents/Code/artrix.dev" = "zed"
"/home/artrix/Documents/Code/tortillas" = "zed"
