require "config.lazy"
require "config.options"
require "config.binds"
require "config.lsp"

-- local base16 = require("base46-extracted").get_theme_tb "base_16"
local theme = require("base46-extracted").get_theme_tb "base_30"
local lighten = require("base46-extracted.colors").change_hex_lightness

-- Syntax
require("base46-extracted").install_integration("syntax", {
   Boolean = { fg = theme.base09 },
   Character = { fg = theme.base08 },
   Conditional = { fg = theme.base0E },
   Constant = { fg = theme.base09 },
   Define = { fg = theme.base0E, sp = "none" },
   Delimiter = { fg = theme.base0F },
   Float = { fg = theme.base09 },
   Variable = { fg = theme.base05 },
   Function = { fg = theme.base0D },
   Identifier = { fg = theme.base08, sp = "none" },
   Include = { fg = theme.base0D },
   Keyword = { fg = theme.base0E },
   Label = { fg = theme.base0A },
   Number = { fg = theme.base09 },
   Operator = { fg = theme.base05, sp = "none" },
   PreProc = { fg = theme.base0A },
   Repeat = { fg = theme.base0A },
   Special = { fg = theme.base0C },
   SpecialChar = { fg = theme.base0F },
   Statement = { fg = theme.base08 },
   StorageClass = { fg = theme.base0A },
   String = { fg = theme.base0B },
   Structure = { fg = theme.base0E },
   Tag = { fg = theme.base0A },
   Todo = { fg = theme.base0A, bg = theme.base01 },
   Type = { fg = theme.base0A, sp = "none" },
   Typedef = { fg = theme.base0A },
})

-- Defaults
require("base46-extracted").install_integration("defaults", {
   Added = { fg = theme.green },
   Removed = { fg = theme.red },
   Changed = { fg = theme.yellow },
   MatchWord = { bg = theme.grey, fg = theme.white },
   Pmenu = { bg = theme.one_bg },
   PmenuSbar = { bg = theme.one_bg },
   PmenuSel = { bg = theme.pmenu_bg, fg = theme.black },
   PmenuThumb = { bg = theme.grey },
   MatchParen = { link = "MatchWord" },
   Comment = { fg = theme.light_grey },
   CursorLineNr = { fg = theme.white },
   LineNr = { fg = theme.grey },
   FloatBorder = { fg = theme.blue },
   FloatTitle = { fg = theme.white, bg = theme.grey },
   NormalFloat = { bg = theme.darker_black },
   NvimInternalError = { fg = theme.red },
   WinSeparator = { fg = theme.line },
   Normal = { fg = theme.base05, bg = theme.black },
   DevIconDefault = { fg = theme.red },
   Debug = { fg = theme.base08 },
   Directory = { fg = theme.base0D },
   Error = { fg = theme.base00, bg = theme.base08 },
   ErrorMsg = { fg = theme.base08, bg = theme.base00 },
   Exception = { fg = theme.base08 },
   FoldColumn = { bg = "none" },
   Folded = { fg = theme.light_grey, bg = theme.black2 },
   IncSearch = { fg = theme.base01, bg = theme.base09 },
   Macro = { fg = theme.base08 },
   ModeMsg = { fg = theme.base0B },
   MoreMsg = { fg = theme.base0B },
   Question = { fg = theme.base0D },
   Search = { fg = theme.base01, bg = theme.base0A },
   Substitute = { fg = theme.base01, bg = theme.base0A },
   SpecialKey = { fg = theme.base03 },
   TooLong = { fg = theme.base08 },
   Visual = { bg = theme.one_bg2 },
   VisualNOS = { fg = theme.base08 },
   WarningMsg = { fg = theme.base08 },
   WildMenu = { fg = theme.base08, bg = theme.base0A },
   Title = { fg = theme.base0D },
   Conceal = { bg = "NONE" },
   Cursor = { fg = theme.base00, bg = theme.base05 },
   NonText = { fg = theme.base03 },
   SignColumn = { fg = theme.base03 },
   ColorColumn = { bg = theme.black2 },
   CursorColumn = { bg = theme.base01 },
   CursorLine = { bg = theme.black2 },
   QuickFixLine = { bg = theme.base01 },
   healthSuccess = { bg = theme.green, fg = theme.black },
   WinBar = { bg = "NONE" },
   WinBarNC = { bg = "NONE" },
   StatusLine = { bg = "NONE" },
   StatusLineNC = { bg = "NONE" },

   -- lazy.nvim
   LazyH1 = { bg = theme.green, fg = theme.black },
   LazyButton = { bg = theme.one_bg, fg = lighten(theme.light_grey, vim.o.bg == "dark" and 10 or -20) },
   LazyH2 = { fg = theme.red, bold = true, underline = true },
   LazyReasonPlugin = { fg = theme.red },
   LazyValue = { fg = theme.teal },
   LazyDir = { fg = theme.base05 },
   LazyUrl = { fg = theme.base05 },
   LazyCommit = { fg = theme.green },
   LazyNoCond = { fg = theme.red },
   LazySpecial = { fg = theme.blue },
   LazyReasonFt = { fg = theme.purple },
   LazyOperator = { fg = theme.white },
   LazyReasonKeys = { fg = theme.teal },
   LazyTaskOutput = { fg = theme.white },
   LazyCommitIssue = { fg = theme.pink },
   LazyReasonEvent = { fg = theme.yellow },
   LazyReasonStart = { fg = theme.white },
   LazyReasonRuntime = { fg = theme.nord_blue },
   LazyReasonCmd = { fg = theme.sun },
   LazyReasonSource = { fg = theme.cyan },
   LazyReasonImport = { fg = theme.white },
   LazyProgressDone = { fg = theme.green },
})
